erDiagram
    AssetFulfillmentDecomp
    FulfillmentAsset
    FulfillmentAssetAttribute
    FulfillmentAssetRelationship
    FulfillmentFalloutRule
    FulfillmentLineAttribute
    FulfillmentLineRel
    FulfillmentLineSourceRel
    FulfillmentOrder
    FulfillmentOrderLineItem
    FulfillmentPlan
    FulfillmentStep
    FulfillmentStepDefinition
    FulfillmentStepDefinitionGroup
    FulfillmentStepDependency
    FulfillmentStepDependencyDef
    FulfillmentStepJeopardyRule
    FulfillmentStepSource
    FulfillmentTaskAssignmentRule
    FulfillmentWorkspace
    FulfillmentWorkspaceItem
    ProdtDecompEnrchVarMap
    ProductDecompEnrichmentRule
    ProductFulfillmentDecompRule
    ProductFulfillmentScenario
    SalesTransactionFulfillReq
    SalesTrxnDeleteEvent
    ValTfrm
    ValTfrmGrp
    FulfillmentAssetRelationship }o--|| FulfillmentAsset : AssociatedFulfillmentAssetId
    FulfillmentStep }o--|| FulfillmentStep : AssignedToId
    FulfillmentStep }o--|| FulfillmentPlan : FulfillmentPlanId
    FulfillmentStep }o--|| FulfillmentStepDefinition : FulfillmentStepDefinitionId
    FulfillmentStepDefinition }o--|| FulfillmentStepDefinitionGroup : AmendGroupId
    FulfillmentStepDependency }o--|| FulfillmentStep : Field
    FulfillmentStepDependency }o--|| FulfillmentStepDependencyDef : DependencyDefinitionId
    FulfillmentStepDependency }o--|| FulfillmentStep : DependsOnStepId
    FulfillmentStepDependency }o--|| FulfillmentStepDefinition : DependsOnStepDefinitionId
    AssetFulfillmentDecomp }o--|| FulfillmentAsset : FulfillmentSourceAssetId
    AssetFulfillmentDecomp }o--|| FulfillmentAsset : FulfillmentTargetAssetId
    ProductFulfillmentScenario }o--|| FulfillmentStepDefinitionGroup : FulfillmentStepDefnGroupId
    FulfillmentStepDependencyDef }o--|| FulfillmentStep : DependsOnStepId
    FulfillmentStepDependencyDef }o--|| FulfillmentStepDefinition : DependsOnStepDefinitionId
    ProductDecompEnrichmentRule }o--|| ValTfrmGrp : ListMappingGroupId
    SalesTransactionFulfillReq }o--|| FulfillmentPlan : PlanId
    SalesTransactionFulfillReq }o--|| SalesTransactionFulfillReq : PreviousRequestId
    FulfillmentOrderLineItem ||--o{ FulfillmentOrder : FulfillmentOrderId