erDiagram
    AttrPicklistExcludedValue
    AttributeCategory
    AttributeDefinition
    AttributePicklist
    AttributePicklistValue
    Product2
    ProductAttributeDefinition
    ProductCategory
    ProductCategoryProduct
    ProductRelatedComponent
    ProductRelationshipType
    AttrPicklistExcludedValue }o--|| Product2 : ProductId
    AttributeDefinition }o--|| AttributePicklist : PicklistId
    AttributePicklistValue }o--|| AttributePicklist : AttributePicklistId
    ProductAttributeDefinition }o--|| AttributeCategory : AttributeCategoryId
    ProductAttributeDefinition }o--|| AttributeDefinition : AttributeDefinitionId
    ProductAttributeDefinition }o--|| Product2 : Product2Id
    ProductCategoryProduct }o--|| ProductCategory : CategoryId
    ProductCategoryProduct }o--|| Product2 : ProductId
    ProductRelatedComponent }o--|| Product2 : ParentProductId
    ProductRelatedComponent }o--|| Product2 : ProductId
    ProductRelatedComponent }o--|| ProductRelationshipType : ProductRelationshipTypeId
    ProductCategoryProduct }o--|| ProductCategory : ProductCategoryId